DROP DATABASE IF EXISTS dnd_database;

CREATE DATABASE dnd_database;
USE dnd_database;

-- Armor and Shields table for defensive gear
CREATE TABLE armor_shields (
	id INT AUTO_INCREMENT PRIMARY KEY,
    type ENUM ('Light', 'Medium', 'Heavy', 'Shield') NOT NULL, 
    name VARCHAR(100),
    AC VARCHAR(100), -- armor class
    strength VARCHAR(100),
    stealth ENUM ('Disadvantage'),
    weight VARCHAR(100),
    cost VARCHAR(100),
    don_time VARCHAR(100),
    doff_time VARCHAR(100)
);

-- Weapons table for melee and `range`d weapons
CREATE TABLE weapons (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,  -- Weapon name
    type VARCHAR(100) NOT NULL,
    cost VARCHAR(100),
    damage VARCHAR(100),
    weight VARCHAR(100),
    properties VARCHAR(100)
);

-- Equipment table for general items (excluding weapons, armor, and shields)
CREATE TABLE equipment (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,  -- Name of the item
    type VARCHAR(100) NOT NULL,  -- Type of equipment (e.g., wand, tool, etc.)
    description TEXT,  -- Item details
    weight FLOAT,  -- Item weight in lbs
    cost VARCHAR(10),  -- Cost in gold pieces (GP)
    tags VARCHAR(100) -- e.g., utility, combat, damage, etc.
);

INSERT INTO armor_shields (id, type, name, AC, strength, stealth, weight, cost, don_time, doff_time) VALUES
(01, 'Light', 'Padded', '11 + Dex Modifier', NULL, 'Disadvantage', '8lb', '5 gp', '1 min', '1 min'),
(02, 'Light', 'Leather', '11 + Dex Modiefier', NULL, NULL, '10 lb', '10 gp', '1 min', '1 min'),
(03, 'Light', 'Studded Leather', '12 + Dex Modifier', NULL, NULL, '13 lb', ' 45 gp', '1 min', '1 min'),
(04, 'Medium', 'Hide', '12 + Dex Modifier (max 2)', NULL, NULL, '12 lb', '10 gp', '5 min', '1 min'),
(05, 'Medium', 'Chain SHirt', '13 + Dex Modifier (max 2)', NULL, NULL, '20 lb', '50 gp', '5 min', '1 min'),
(06, 'Medium', 'Scale Mail', '14 + Dex Modifier (max 2)', NULL, 'Disadvantage', '45 lb', '50 gp', '5 min', '1 min'),
(07, 'Medium', 'Spiked Armor', '14 + Dex Modifier (max 2)', NULL, 'Disadvantage', '45 lb', '75 gp', '5 min', '1 min'),
(08, 'Medium', 'Breastplate', '14 + Dex Modifier (max 2)', NULL, NULL, '20 lb', '400 gp', '5 min', '1 min'),
(09, 'Medium', 'Halfplate', '15 + Dex Modifier (max 2)', NULL, 'Disadvantage', ' 40 lb', '750 gp', '5 min', '1 min'),
(10, 'Heavy', 'Ring Mail', '14', NULL, 'Disadvantage', '40 lb', '30 gp', '10 min', '5 min'),
(11, 'Heavy', 'Chain Mail', '16', '13', 'Disadvantage', '55 lb', '75 gp', '10 min', '5 min'),
(12, 'Heavy', 'Splint', '17', '15', 'Disadvantage', '60 lb', '200 gp', '10 min', '5 min'),
(13, 'Heavy', 'Plate', '18', '15', 'Disadvantage', '65 lb', '1500 gp', '10 min', '5 min'),
(14, 'Shield', 'Shield', '+2', NULL, NULL, '6 lb', '10 gp', '1 action', '1 action')
;

-- Weapons Table
INSERT INTO weapons (id, name, type, cost, damage, weight, properties) VALUES
('01', 'Dagger', 'Simple Melee', '2 gp', '1d4 piercing', 1, 'Finesse, light, thrown (20/60)'),
('02', 'Greatsword', 'Martial Melee', '50 gp', '2d6 slashing', 6, 'Heavy, two-handed'),
('03', 'Longsword', 'Martial Melee', '15 gp', '1d8 slashing', 3, 'Versatile (1d10)'),
('04', 'Shortsword', 'Martial Melee', '10 gp', '1d6 piercing', 2, 'Finesse, light'),
('05', 'Rapier', 'Martial Melee', '25 gp', '1d8 piercing', 2, 'Finesse'),
('06', 'Scimitar', 'Martial Melee', '25 gp', '1d6 slashing', 3, 'Finesse, light'),
('07', 'Greataxe', 'Martial Melee', '30 gp', '1d12 slashing', 7, 'Heavy, two-handed'),
('08', 'Battleaxe', 'Martial Melee', '10 gp', '1d8 slashing', 4, 'Versatile (1d10)'),
('09', 'Warhammer', 'Martial Melee', '15 gp', '1d8 bludgeoning', 2, 'Versatile (1d10)'),
('10', 'Maul', 'Martial Melee', '10 gp', '2d6 bludgeoning', 10, 'Heavy, two-handed'),
('11', 'Mace', 'Simple Melee', '5 gp', '1d6 bludgeoning', 4, NULL),
('12', 'Club', 'Simple Melee', '1 sp', '1d4 bludgeoning', 2, 'Light'),
('13', 'Quarterstaff', 'Simple Melee', '2 sp', '1d6 bludgeoning', 4, 'Versatile (1d8)'),
('14', 'Spear', 'Simple Melee', '1 gp', '1d6 piercing', 3, 'Thrown (20/60), versatile (1d8)'),
('15', 'Halberd', 'Martial Melee', '20 gp', '1d10 slashing', 6, 'Heavy, reach, two-handed'),
('16', 'Glaive', 'Martial Melee', '20 gp', '1d10 slashing', 6, 'Heavy, reach, two-handed'),
('17', 'Pike', 'Martial Melee', '5 gp', '1d10 piercing', 18, 'Heavy, reach, two-handed'),
('18', 'Trident', 'Martial Melee', '5 gp', '1d6 piercing', 4, 'Thrown (20/60), versatile (1d8)'),
('19', 'Whip', 'Martial Melee', '2 gp', '1d4 slashing', 3, 'Finesse, reach'),
('20', 'Morningstar', 'Martial Melee', '15 gp', '1d8 piercing', 4, NULL),
('21', 'Sickle', 'Simple Melee', '1 gp', '1d4 slashing', 2, 'Light'),
('22', 'Handaxe', 'Simple Melee', '5 gp', '1d6 slashing', 2, 'Light, thrown (20/60)'),
('23', 'Light Hammer', 'Simple Melee', '2 gp', '1d4 bludgeoning', 2, 'Light, thrown (20/60)'),
('24', 'Javelin', 'Simple Melee', '5 sp', '1d6 piercing', 2, 'Thrown (30/120)'),
('25', 'Lance', 'Martial Melee', '10 gp', '1d12 piercing', 6, 'Reach, special'),
('26', 'Net', 'Martial Ranged', '1 gp', NULL, 3, 'Special, thrown (5/15)'),
('27', 'Longbow', 'Martial Ranged', '50 gp', '1d8 piercing', 2, 'Ammunition (150/600), heavy, two-handed'),
('28', 'Shortbow', 'Simple Ranged', '25 gp', '1d6 piercing', 2, 'Ammunition (80/320), two-handed'),
('29', 'Crossbow, Light', 'Simple Ranged', '25 gp', '1d8 piercing', 5, 'Ammunition (80/320), loading, two-handed'),
('30', 'Crossbow, Heavy', 'Martial Ranged', '50 gp', '1d10 piercing', 18, 'Ammunition (100/400), heavy, loading, two-handed'),
('31', 'Hand Crossbow', 'Martial Ranged', '75 gp', '1d6 piercing', 3, 'Ammunition (30/120), light, loading'),
('32', 'Blowgun', 'Martial Ranged', '10 gp', '1 piercing', 1, 'Ammunition (25/100), loading'),
('33', 'Sling', 'Simple Ranged', '1 sp', '1d4 bludgeoning', 0, 'Ammunition (30/120)'),
('34', 'Boomerang', 'Simple Ranged', '1 gp', '1d4 bludgeoning', 1, 'Thrown (60/120)'),
('35', 'Yklwa', 'Martial Melee', '1 gp', '1d8 piercing', 2, 'Thrown (10/30)'),
('36', 'Spiked Chain', 'Martial Melee', '25 gp', '1d6 slashing', 5, 'Finesse, reach, special'),
('37', 'Double-Bladed Scimitar', 'Martial Melee', '100 gp', '2d4 slashing', 6, 'Two-handed, special'),
('38', 'Greatclub', 'Simple Melee', '2 sp', '1d8 bludgeoning', 10, 'Two-handed'),
('39', 'Falchion', 'Martial Melee', '75 gp', '2d4 slashing', 8, 'Heavy, two-handed'),
('40', 'Katana', 'Martial Melee', '30 gp', '1d10 slashing', 3, 'Versatile (1d12)'),
('41', 'Naginata', 'Martial Melee', '25 gp', '1d10 slashing', 7, 'Reach, two-handed'),
('42', 'Tetsubo', 'Martial Melee', '20 gp', '2d6 bludgeoning', 12, 'Heavy, two-handed'),
('43', 'Chakram', 'Martial Ranged', '5 gp', '1d6 slashing', 1, 'Thrown (30/60), light'),
('44', 'Kukri', 'Martial Melee', '10 gp', '1d4 slashing', 1, 'Finesse, light'),
('45', 'Sai', 'Martial Melee', '5 gp', '1d4 bludgeoning', 1, 'Finesse, light'),
('46', 'Kama', 'Martial Melee', '8 gp', '1d6 slashing', 2, 'Light'),
('47', 'War Pick', 'Martial Melee', '5 gp', '1d8 piercing', 2, NULL),
('48', 'Shuriken', 'Martial Ranged', '1 gp', '1d4 piercing', 0.5, 'Thrown (20/60), light'),
('49', 'Blowdart', 'Martial Ranged', '5 sp', '1 piercing', 0.5, 'Ammunition (25/100)'),
('50', 'Punch Dagger', 'Martial Melee', '2 gp', '1d4 piercing', 1, 'Finesse, light'),
('51', 'Whalebone Club', 'Simple Melee', '1 gp', '1d6 bludgeoning', 5, NULL)
;


-- Equipment Table
INSERT INTO equipment (id, name, type, description, weight, cost, tags) VALUES
('001', 'Backpack', 'Container', 'A sturdy pack to carry gear, with straps for easy transport.', 5, '2 gp', 'utility, storage'),
('002', 'Bedroll', 'Adventuring Gear', 'A warm blanket and bedding roll for sleeping outdoors.', 5, '1 gp', 'utility, camping'),
('003', 'Rope, hempen (50 ft)', 'Adventuring Gear', 'A 50-foot length of sturdy hemp rope.', 10, '1 gp', 'utility, climbing'),
('004', 'Torch', 'Adventuring Gear', 'A wooden torch that provides light when lit.', 1, '1 cp', 'utility, light'),
('005', 'Waterskin', 'Container', 'A leather container that holds up to 4 pints of liquid.', 5, '2 sp', 'utility, hydration'),
('006', 'Rations (1/day)', 'Adventuring Gear', 'Preserved food sufficient for one day of meals.', 2, '5 sp', 'utility, sustenance'),
('007', 'Tinderbox', 'Adventuring Gear', 'A small box containing flint, fire steel, and tinder.', 1, '5 sp', 'utility, fire-starting'),
('008', 'Lantern, hooded', 'Adventuring Gear', 'A lantern with a hood to control light emission.', 2, '5 gp', 'utility, light'),
('009', 'Caltrops (bag of 20)', 'Adventuring Gear', 'Sharp spikes that can slow down pursuers.', 2, '1 gp', 'combat, trap'),
('010', 'Ball Bearings (bag of 1,000)', 'Adventuring Gear', 'Tiny metal balls that can trip creatures.', 2, '1 gp', 'combat, trap'),
('011', 'Crowbar', 'Tool', 'A metal bar with a curved end used for prying.', 5, '2 gp', 'utility, leverage'),
('012', 'Hammer', 'Tool', 'A basic tool for driving nails or breaking objects.', 3, '1 gp', 'utility, construction'),
('013', 'Piton', 'Adventuring Gear', 'A metal spike used for anchoring ropes.', 0.5, '5 cp', 'utility, climbing'),
('014', 'Shovel', 'Tool', 'A tool for digging.', 5, '2 gp', 'utility, excavation'),
('015', 'Grappling Hook', 'Adventuring Gear', 'A hook used to secure ropes to surfaces.', 4, '2 gp', 'utility, climbing'),
('016', 'Mirror, steel', 'Adventuring Gear', 'A small steel mirror.', 0.5, '5 gp', 'utility, observation'),
('017', 'Signal Whistle', 'Adventuring Gear', 'A whistle used to signal others.', 0, '5 cp', 'utility, communication'),
('018', 'Soap', 'Adventuring Gear', 'A bar of soap for cleaning.', 0, '2 cp', 'utility, hygiene'),
('019', 'Tent, two-person', 'Adventuring Gear', 'A canvas tent that can accommodate two people.', 20, '2 gp', 'utility, camping'),
('020', 'Whetstone', 'Tool', 'A stone used to sharpen blades.', 1, '1 cp', 'utility, maintenance'),
('021', 'Vial', 'Container', 'A small glass container for liquids.', 0, '1 gp', 'utility, storage'),
('022', 'Ink (1 ounce bottle)', 'Adventuring Gear', 'A bottle of ink for writing.', 0, '10 gp', 'utility, writing'),
('023', 'Ink Pen', 'Adventuring Gear', 'A pen for writing with ink.', 0, '2 cp', 'utility, writing'),
('024', 'Parchment (one sheet)', 'Adventuring Gear', 'A sheet of parchment for writing.', 0, '1 sp', 'utility, writing'),
('025', 'Paper (one sheet)', 'Adventuring Gear', 'A sheet of paper for writing.', 0, '2 sp', 'utility, writing'),
('026', 'Sealing Wax', 'Adventuring Gear', 'Wax used to seal letters.', 0, '5 sp', 'utility, correspondence'),
('027', 'Case, map or scroll', 'Container', 'A cylindrical case for carrying maps or scrolls.', 1, '1 gp', 'utility, storage'),
('028', 'Magnifying Glass', 'Tool', 'A lens that magnifies small objects.', 0, '100 gp', 'utility, investigation'),
('029', 'Spyglass', 'Tool', 'A telescope that magnifies distant objects.', 1, '1,000 gp', 'utility, observation'),
('030', 'Lock', 'Adventuring Gear', 'A padlock to secure items.', 1, '10 gp', 'utility, security'),
('031', 'Manacles', 'Adventuring Gear', 'Metal restraints for binding hands or feet.', 6, '2 gp', 'utility, restraint'),
('032', 'Hourglass', 'Tool', 'A device to measure time.', 1, '25 gp', 'utility, timekeeping'),
('033', 'Holy Symbol', 'Adventuring Gear', 'A symbol representing a deity.', 1, '5 gp', 'utility, religious'),
('034', 'Healer’s Kit', 'Adventuring Gear', 'A kit containing bandages and salves.', 3, '5 gp', 'utility, healing'),
('035', 'Alchemist’s Supplies', 'Tool', 'Tools for creating alchemical mixtures.', 8, '50 gp', 'utility, crafting'),
('036', 'Brewer’s Supplies', 'Tool', 'Equipment for brewing beverages.', 9, '20 gp', 'utility, crafting'),
('037', 'Calligrapher’s Supplies', 'Tool', 'Tools for fine handwriting.', 5, '10 gp', 'utility, writing'),
('038', 'Carpenter’s Tools', 'Tool', 'Tools for woodworking.', 6, '8 gp', 'utility, crafting'),
('039', 'Cartographer’s Tools', 'Tool', 'Instruments for mapmaking.', 6, '15 gp', 'utility, navigation'),
('040', 'Cobbler’s Tools', 'Tool', 'Tools for making and repairing shoes.', 5, '5 gp', 'utility, crafting'),
('041', 'Climber’s Kit', 'Tool', 'A set of special pitons, boot tips, gloves, and a harness to aid in climbing.', 12, '25 gp', 'utility, climbing'),
('042', 'Fishing Tackle', 'Tool', 'A kit containing a rod, line, hooks, and bait for catching fish.', 4, '1 gp', 'utility, food'),
('043', 'Hunting Trap', 'Adventuring Gear', 'A steel trap used to catch animals or restrain creatures.', 25, '5 gp', 'utility, trap'),
('044', 'Oil (flask)', 'Adventuring Gear', 'A flask of oil that can be used to light fires or lubricate mechanisms.', 1, '1 sp', 'utility, fire'),
('045', 'Holy Water (flask)', 'Adventuring Gear', 'A flask of water blessed for use against undead and fiends.', 1, '25 gp', 'utility, combat'),
('046', 'Antitoxin (vial)', 'Adventuring Gear', 'A vial that grants advantage on saving throws against poison.', 0, '50 gp', 'utility, healing'),
('047', 'Alchemist’s Fire (flask)', 'Adventuring Gear', 'A sticky, adhesive fluid that ignites when exposed to air.', 1, '50 gp', 'utility, combat'),
('048', 'Acid (vial)', 'Adventuring Gear', 'A vial of corrosive acid that can burn through materials.', 1, '25 gp', 'utility, combat'),
('049', 'Perfume (vial)', 'Adventuring Gear', 'A vial of fragrant liquid used for scenting.', 0, '5 gp', 'utility, social'),
('050', 'Signet Ring', 'Adventuring Gear', 'A ring bearing a family crest or symbol.', 0, '5 gp', 'utility, identification'),
('051', 'Spellbook', 'Adventuring Gear', 'A book containing a wizard’s spells.', 3, '50 gp', 'utility, magic'),
('052', 'Component Pouch', 'Adventuring Gear', 'A pouch to hold spellcasting components.', 2, '25 gp', 'utility, magic'),
('053', 'Arcane Focus (crystal)', 'Adventuring Gear', 'A crystal used as a focus for arcane spells.', 1, '10 gp', 'utility, magic'),
('054', 'Druidic Focus (wooden staff)', 'Adventuring Gear', 'A staff used as a focus for druidic spells.', 4, '5 gp', 'utility, magic'),
('055', 'Holy Symbol (amulet)', 'Adventuring Gear', 'An amulet representing a deity.', 1, '5 gp', 'utility, religious'),
('056', 'Thieves’ Tools', 'Tool', 'A set of tools for picking locks and disarming traps.', 1, '25 gp', 'utility, stealth'),
('057', 'Disguise Kit', 'Tool', 'A kit containing cosmetics and props for disguises.', 3, '25 gp', 'utility, deception'),
('058', 'Forgery Kit', 'Tool', 'A kit with tools for creating forgeries.', 5, '15 gp', 'utility, deception'),
('059', 'Herbalism Kit', 'Tool', 'A kit for identifying and using herbs.', 3, '5 gp', 'utility, healing'),
('060', 'Navigator’s Tools', 'Tool', 'Instruments used for navigation at sea.', 2, '25 gp', 'utility, navigation'),
('061', 'Poisoner’s Kit', 'Tool', 'A kit for crafting and handling poisons.', 2, '50 gp', 'utility, crafting'),
('062', 'Tinker’s Tools', 'Tool', 'Tools for repairing and crafting small objects.', 10, '50 gp', 'utility, crafting'),
('063', 'Weaver’s Tools', 'Tool', 'Tools for weaving cloth.', 5, '1 gp', 'utility, crafting'),
('064', 'Woodcarver’s Tools', 'Tool', 'Tools for carving wood.', 5, '1 gp', 'utility, crafting'),
('065', 'Mason’s Tools', 'Tool', 'Tools for working with stone.', 8, '10 gp', 'utility, crafting'),
('066', 'Smith’s Tools', 'Tool', 'Tools for metalworking.', 8, '20 gp', 'utility, crafting'),
('067', 'Painter’s Supplies', 'Tool', 'Supplies for painting.', 5, '10 gp', 'utility, art'),
('068', 'Jeweler’s Tools', 'Tool', 'Tools for crafting jewelry.', 2, '25 gp', 'utility, crafting'),
('069', 'Leatherworker’s Tools', 'Tool', 'Tools for working with leather.', 5, '5 gp', 'utility, crafting'),
('070', 'Potter’s Tools', 'Tool', 'Tools for shaping clay.', 3, '10 gp', 'utility, crafting'),
('071', 'Musical Instrument (lute)', 'Tool', 'A stringed instrument used for music.', 2, '35 gp', 'utility, performance'),
('072', 'Musical Instrument (flute)', 'Tool', 'A wind instrument used for music.', 1, '2 gp', 'utility, performance'),
('073', 'Cook’s Utensils', 'Tool', 'A kit for preparing and cooking meals.', 8, '1 gp', 'utility, crafting, food'),
('074', 'Glassblower’s Tools', 'Tool', 'Tools used for shaping molten glass.', 5, '30 gp', 'utility, crafting'),
('075', 'Navigator’s Journal', 'Adventuring Gear', 'A weathered logbook for recording sea journeys.', 1, '5 gp', 'utility, navigation'),
('076', 'Scribe’s Supplies', 'Tool', 'Tools for copying manuscripts and documents.', 3, '10 gp', 'utility, writing'),
('077', 'Dice Set', 'Gaming Set', 'A set of small dice used for games of chance.', 0, '1 sp', 'utility, gaming'),
('078', 'Deck of Cards', 'Gaming Set', 'A full deck used for card games and gambling.', 0, '5 sp', 'utility, gaming'),
('079', 'Dragonchess Set', 'Gaming Set', 'A three-tiered chess-like strategy game.', 0.5, '1 gp', 'utility, gaming'),
('080', 'Three-Dragon Ante Set', 'Gaming Set', 'A card game popular among adventurers.', 0.5, '1 gp', 'utility, gaming'),
('081', 'Ball of Twine (100 ft)', 'Adventuring Gear', 'A long roll of twine useful for light-duty tasks.', 1, '1 sp', 'utility, crafting'),
('082', 'Chalk (10 pieces)', 'Adventuring Gear', 'Colored chalk useful for marking walls and objects.', 0, '1 sp', 'utility, marking'),
('083', 'Ladder (10 ft)', 'Adventuring Gear', 'A wooden ladder useful for climbing.', 25, '1 sp', 'utility, climbing'),
('084', 'Bucket', 'Container', 'A wooden or metal bucket for carrying liquids.', 2, '5 cp', 'utility, hauling'),
('085', 'Blanket', 'Adventuring Gear', 'A warm wool blanket for comfort or warmth.', 3, '5 sp', 'utility, camping'),
('086', 'Chain (10 ft)', 'Adventuring Gear', 'A sturdy iron chain useful for restraint or lifting.', 10, '5 gp', 'utility, restraint'),
('087', 'Portable Ram', 'Tool', 'A reinforced beam used to break doors or barriers.', 35, '4 gp', 'utility, force'),
('088', 'Harness, Mule', 'Tack', 'Straps and buckles used to hitch a beast of burden.', 10, '2 gp', 'utility, travel'),
('089', 'Saddle, Pack', 'Tack', 'A saddle for carrying gear on a pack animal.', 15, '5 gp', 'utility, storage'),
('090', 'Saddle, Riding', 'Tack', 'A saddle made for riding animals.', 25, '10 gp', 'utility, travel'),
('091', 'Bit and Bridle', 'Tack', 'A headgear set used to control a mount.', 1, '2 gp', 'utility, travel'),
('092', 'Feed (per day)', 'Adventuring Gear', 'A day’s worth of feed for a horse or pack animal.', 10, '5 cp', 'utility, animal care'),
('093', 'Snowshoes', 'Adventuring Gear', 'Large footwear to walk over deep snow.', 4, '2 gp', 'utility, travel'),
('094', 'Waterskin (insulated)', 'Container', 'A waterskin insulated for extreme environments.', 6, '3 gp', 'utility, hydration'),
('095', 'Bandolier', 'Container', 'A shoulder-worn belt with loops for storing small gear.', 2, '1 gp', 'utility, storage'),
('096', 'Climbing Spikes', 'Adventuring Gear', 'Metal spikes worn on boots to climb icy or sheer surfaces.', 4, '3 gp', 'utility, climbing'),
('097', 'Tent, four-person', 'Adventuring Gear', 'A larger canvas tent suited for four people.', 30, '4 gp', 'utility, camping'),
('098', 'Folding Chair', 'Adventuring Gear', 'A collapsible wooden chair for comfort during rests.', 3, '1 gp', 'utility, comfort'),
('099', 'Writing Desk (portable)', 'Tool', 'A small foldable writing surface with compartments.', 10, '20 gp', 'utility, writing'),
('100', 'Mess Kit', 'Adventuring Gear', 'A metal kit with utensils and dishware for eating.', 1, '2 sp', 'utility, food'),
('101', 'Spool of Wire (25 ft)', 'Adventuring Gear', 'A thin but strong metallic wire spool.', 1, '1 gp', 'utility, trap, tinkering'),
('102', 'Pulley', 'Tool', 'A device that aids in lifting heavy loads.', 5, '1 gp', 'utility, lifting'),
('103', 'Measuring Tape', 'Tool', 'A retractable tape marked with distances.', 0.5, '5 sp', 'utility, measurement'),
('104', 'Saddlebag', 'Container', 'A pair of pouches for carrying items on a mount.', 8, '4 gp', 'utility, storage'),
('105', 'Goggles, Tinted', 'Adventuring Gear', 'Eyewear that reduces glare and protects against dust.', 0.5, '10 gp', 'utility, vision'),
('106', 'Earplugs (waxed cotton)', 'Adventuring Gear', 'Simple plugs for blocking out sound.', 0, '3 sp', 'utility, sensory'),
('107', 'Sling Bag', 'Container', 'A simple shoulder bag for carrying small items.', 2, '5 sp', 'utility, storage'),
('108', 'Tarp', 'Adventuring Gear', 'A durable cloth for covering or shelter.', 5, '1 gp', 'utility, camping'),
('109', 'Firewood (bundle)', 'Adventuring Gear', 'A bundle of dry wood used for campfires.', 10, '1 sp', 'utility, fire'),
('110', 'Broom', 'Tool', 'A simple broom for sweeping.', 4, '2 sp', 'utility, cleaning'),
('111', 'Handbell', 'Adventuring Gear', 'A small bell used to signal or alert others.', 1, '1 gp', 'utility, communication'),
('112', 'Compass', 'Tool', 'A small magnetic device used to determine cardinal directions.', 0.5, '25 gp', 'utility, navigation, travel')
;
